#program to demonstrate Exception Handling

try:
    a=10
    print(a)
    print(b)
except:
    print("Exception Occurred")
